namespace Dhcpr.Dhcp.Core.Protocol;

// See: https://www.iana.org/assignments/bootp-dhcp-parameters/bootp-dhcp-parameters.xhtml
// I would like to complete this list, so that the dropdown shows the names, not critical though.
// We can just add the remaining ones as we use them.
public enum DhcpOptionCode : byte
{
    Pad = 0,
    SubnetMask = 1,
    TimeOffset = 2,
    Router = 3,
    TimeServer = 4,
    NameServer = 5,
    DomainServer = 6,
    LogServer = 7,
    QuotesServer = 8,
    LPRServer = 9,
    ImpressServer = 10,
    RLPServer = 11,
    Hostname = 12,
    BootFileSize = 13,
    MeritDumpFile = 14,
    DomainName = 15,
    SwapServer = 16,
    RootPath = 17,
    ExtensionFile = 18,
    IPForwarding = 19,
    SourceRouting = 20,
    PolicyFilter = 21,
    MaxDatagramReassemblySize = 22,
    DefaultIPTimeToLive = 23,
    PathMaximumTransmissionUnitTimeout = 24,
    PathMaximumTransmissionUnitPlateau = 25,
    InterfaceMaximumTransmissionUnit = 26,
    AllSubnetsAreLocal = 27,
    BroadcastAddress = 28,
    PerformMaskDiscovery = 29,
    ProvideMaskToOthers = 30,
    PerformRouterDiscovery = 31,
    RouterSolicitationAddress = 32,
    StaticRoute = 33,
    Trailers = 34,
    ArpTimeout = 35,
    EthernetEncapsulation = 36,
    DefaultTcpTimeToLive = 37,
    TcpKeepAliveInterval = 38,
    TcpKeepAliveGarbage = 39,
    NisDomain = 40,
    NisServers = 41,
    NtpServers = 42,
    VendorSpecific = 43,
    NetBiosNameServers = 44,
    NetBiosDatagramDistribution = 45,
    NetBiosNodeType = 46,
    NetBiosScope = 47,
    XWindowFontServer = 48,
    XWindowManager = 49,
    AddressRequest = 50,
    AddressLeaseTime = 51,
    Overload = 52,
    DhcpMessageType = 53,
    DhcpServerId = 54,
    ParameterRequestList = 55,
    DhcpErrorMessage = 56,
    DhcpMaxMessageSize = 57,
    DhcpRenewalTime=58,
    DhcpRebindingTime=59,
    ClassIdentifier=60,
    ClientIdentifier=61,
    NetwareIPDomain = 62,
    NetwareIPOption = 63,
    NisDomainName = 64,
    NisServerAddress = 65,
    TftpServerName = 66,
    BootFileName = 67,
    HomeAgentAddresses = 68,
    SMTPServer = 69,
    POP3Server = 70,
    NNTPServer = 71,
    WWWServer = 72,
    FingerServer = 73,
    IRCServer = 74,
    StreetTalkServer = 75,
    STDirectoryAssistantAddresses = 76,
    UserClass = 77,
    DirectoryAgent = 78,
    ServiceScope = 79,
    RapidCommit = 80, // This one also does not have a length.
    ClientFullyQualifiedDomainName = 81,
    // TODO: Complete this list.
    
    End = 255
}