services:
  dns:
    image: harbor.instigaterevolution.com/instigaterevolution/dhcpr/dns:dev
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "8080:8080"
      - "65353:53"
    volumes:
      - blog-data:/data

volumes:
  blog-data:
